theme: just-the-docs
github: [metadata]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

safe: false

plugins:
  - "jekyll-github-metadata"

title: Ted Lang Docs
description: Ted Programming Language Documentations
baseurl: "/"
url: "https://docs.ted-lang.org" # the base hostname & protocol for your site, e.g. http://example.com

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023 <a href=\"https://wqzhao.org\" target=\"_blank\">Wuqiong Zhao</a> (Teddy van Jerry). Distributed under <a href=\"https://github.com/ted-lang/ted/blob/main/LICENSE\" target=\"_blank\">GPL-3.0 License</a>."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/ted-lang/ted" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# for mathjax
compress_html:
  blanklines: true
mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'

# External navigation links
nav_external_links:
  - title: Ted Homepage
    url: https://ted-lang.org
  - title: Ted on GitHub
    url: https://github.com/ted-lang

callouts:
  warning:
    title: Warning
    color: yellow
  hint:
    title: Hint
    color: grey-lt
  important:
    title: Important
    color: green
  note:
    title: Note
    color: grey-dk
  tip:
    title: Tip
    color: blue
  caution:
    title: Caution
    color: red
  error:
    title: Error
    color: pink
  attention:
    title: Attention
    color: purple

exclude:
  - Gemfile
  - Gemfile.lock
  - assets/css/just-the-docs-switchable-src.css
  - _sass # I have used pure CSS now
